# Generated by Django 3.2.6 on 2021-08-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyweather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsposition',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
