# Generated by Django 3.2.6 on 2021-08-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyweather', '0002_alter_gpsposition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsposition',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
